# modgodb database connection config
[MongoDB]
DBURL = "localhost:27017"
DBName = "databasename"
UserName = "username"
Password = "password"

[Gateway]
APIAddress = "https://testnet.fsn.dev/api"
AverageBlockTime = 13 # seconds

[Sync]
Overwrite = false # if true overwrite exist
JobCount = 4 # job count
WaitInterval = 6 # wait seconds to get latest block
Stable = 0 # suggest > 30 for mainnet
Start = 0 # 0 means the latest synced
End = 0 # 0 means endless

[Distribute]

[[Distribute.Exchanges]]
Pairs = "XXX"
Exchange = "0x1111111111111111111111111111111111111111"
Token = "0x2222222222222222222222222222222222222222"
Percentage = 40.0
CreationHeight = 2300000

[[Distribute.Exchanges]]
Pairs = "YYY"
Exchange = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
Token = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
Percentage = 60.0
CreationHeight = 2300000
