# modgodb database connection config
[MongoDB]
DBURL = "localhost:27017"
DBName = "databasename"
UserName = "username"
Password = "password"

[Gateway]
APIAddress = "https://testnet.fsn.dev/api"
AverageBlockTime = 13 # seconds

[Sync]
JobCount = 4 # job count
WaitInterval = 6 # wait seconds to get latest block
Stable = 0 # suggest > 30 for mainnet
UpdateLiquidity = true # switch to update liquidity per day
UpdateVolume = true # switch to update volume per day

[Distribute]
Enable = false
DryRun = true # dry run won't send tx
SaveDB = true # save reward result to database

RewardToken = "0xC20b5E92E1ce63Af6FE537491f75C19016ea5fb4"
StartHeight = 2510000
StableHeight = 30

AddNodeRewards = "6600000000000000000000"
AddNoVolumeRewards = "250000000000000000000"

ByLiquidCycle = 6600
ByLiquidRewards = "9900000000000000000000"
ByLiquidKeystoreFile = "keystore file path"
ByLiquidPasswordFile = "password file path"

ByVolumeCycle = 100
ByVolumeRewards = "250000000000000000000"
ByVolumeKeystoreFile = "keystore file path"
ByVolumePasswordFile = "password file path"
QuickSettleVolumeRewards = true

[[Exchanges]]
Pairs = "ANY"
Exchange = "0x049ddc3cd20ac7a2f6c867680f7e21de70aca9c3"
Token = "0x0c74199D22f732039e843366a236Ff4F61986B32"
CreationHeight = 2545600
LiquidWeight = 2
TradeWeight = 1

[[Exchanges]]
Pairs = "aUSDT"
Exchange = "0x78917333bec47cee1022b31a136d31feff90d6fb"
Token = "0xc7c64ac6d46be3d6ea318ec6276bb55291f8e496"
CreationHeight = 2730000
LiquidWeight = 1
TradeWeight = 1
